language: ruby
cache: bundler
rvm:
- 2.3.0
script: "./_bin/deploy"
branches:
  only:
    - master
env:
  global:
    - GITHUB_REPO_SLUG=gavinrozzi/trentonwatch
    - secure: "HDmfKTI+eIo560H/cqw5qeVB1GU0SaQde9rEXPqqSqO6TmApICJxp2h/LMyinnQBJYVnsOfKAwjK1kdPCH6Xt+EAyaesnTX1a1+KhwPkmd7CE2R4mJNy4V49nIHHeW9wc6yjrgzaFVKJB5mkoWjKuI+cIq9KCLUulipwanY6MMoN8vZRN/Cgx3MY5Ygp8UeWfTuysUo8f1fJMzYdOD/NgDEaMN1wCI4NLOSMk7JTA9DK3PHIAEB/TbhualpSqLkB+Xiyfc6KLURYCLvdkIVL4n8Udmpw5SXoz/5fs2kLM/ydT//T7xgvdCoLDvZ/Xxg5y7gj40UyRXMyvcdYLFDWa4E5lCkZzf3Des8lXQnHrGjW6x+lheETgyTiBXzGOaFXbtUOnzeBlnmsXbkBftnK7E5YhUsuz39gMw0eNF2hUIYheAFulL0Z45Q5LeJzB4kXdNBJp+hKzaiaT54sxCMmUOg6x0YNQ28l6kgVqYrOL2SF4Giw8YZtSGQwF68ddD7oy63XJqfJABDiv1O1PRO5Va/JqnUcv8UouJm+VQwvjuPYcq5owIPl/oWFX3Y+SbRoPJ7SEkJvBGcCKCkyKotYYKAUmPFj9rkNcmahYT5eRZm2jbOGZyqxSjWIt0PrcBB86R6hScZ2V8T2pXkt/L90tsdFech2UuCn+lHkxxkXUIU="
